# Torch Tensors Fundamentals 

In [2]:
import torch

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9903, 0.2783, 0.3345],
        [0.2292, 0.8282, 0.7592]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
rand_tensor.shape

torch.Size([2, 3])

In [10]:
shape = (2,3,3)
rand_tensor = torch.rand(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")

Random Tensor: 
 tensor([[[0.9741, 0.2576, 0.9110],
         [0.2437, 0.2616, 0.8566],
         [0.6134, 0.6544, 0.8245]],

        [[0.5022, 0.6009, 0.6560],
         [0.9621, 0.4569, 0.9431],
         [0.3641, 0.6739, 0.5343]]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [13]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [18]:
## Get first row
print(tensor[0,:])
## Get first column
print(tensor[:,0])
## Get last column
print(tensor[:,-1])
## Get first rows first 2 columns
print(tensor[0,0:2])

tensor([0.1188, 0.3065, 0.5714, 0.0875])
tensor([0.1188, 0.8751, 0.4754])
tensor([0.0875, 0.2719, 0.8729])
tensor([0.1188, 0.3065])


In [33]:
a = torch.empty(0, dtype=torch.int)
a.size().numel()


0

In [61]:
a = torch.rand(2,2)
 
a[0,0].item()


0.3374430537223816

In [62]:
x = {1: 'a', 2: 'b'}
len(x)

2